groups:
  - name: PostgresDown
    rules:
      - alert: PostgresDown
        expr: pg_up < 1
        for: 1s
        labels:
          severity: warning
        annotations:
          summary: "Postgres access is down"
          description: "Postgres exporter didn't reponse"