FROM nginx:stable-alpine3.20
ARG KIBANA_PASSWD
COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template
RUN apk add --no-cache apache2-utils openssl
RUN htpasswd -b -c /etc/nginx/.htpasswd admin $KIBANA_PASSWD
