# Generated by Django 5.1 on 2024-09-05 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_0', models.PositiveIntegerField()),
                ('score_1', models.PositiveIntegerField()),
                ('score_2', models.PositiveIntegerField()),
                ('score_3', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('max_player', models.PositiveIntegerField()),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.score')),
            ],
        ),
    ]
