# Generated by Django 5.1 on 2024-09-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_0',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_1',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_2',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_3',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
