# Generated by Django 5.1 on 2024-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_game_duration_alter_game_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
