# Generated by Django 5.1 on 2024-10-29 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('playerId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('profilePicture', models.CharField()),
                ('elo', models.PositiveSmallIntegerField()),
                ('friends', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')])),
            ],
        ),
    ]
