# Generated by Django 5.1 on 2024-11-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
    ]
